version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
    command: npm start

  # Production service
  app-prod:
    build: .
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
    restart: unless-stopped 